Repository AY2021S1-CS2103-W14-1/tp, pull requests merged in 2020-10, with the labels that each got.

#32 Branch update config
  _config.yml
  docs/_config.yml
Labels: documentation

#73 Remove Email and Address from Person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.Enhancements.Persons

#75 Set up property constructor and fields
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/id/Id.java
  src/main/java/seedu/address/model/id/IdManager.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/property/Address.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/PropertyName.java
  src/main/java/seedu/address/model/property/PropertyType.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/id/IdManagerTest.java
  src/test/java/seedu/address/model/id/IdTest.java
  src/test/java/seedu/address/model/price/PriceTest.java
  src/test/java/seedu/address/model/property/AddressTest.java
  src/test/java/seedu/address/model/property/PropertyNameTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/PropertyTypeTest.java
Labels: type.Enhancements.Properties

#85 Calendar property id branch
  src/main/java/seedu/address/model/CalendarPropertyId.java
Labels: enhancement, type.Task

#88 Calendar bidder id branch
  src/main/java/seedu/address/model/CalendarBidderId.java
Labels: enhancement, type.Task

#87 Add CalendarTime
  src/main/java/seedu/address/logic/commands/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/parser/ViewCalendarParser.java
  src/main/java/seedu/address/model/CalendarTime.java
Labels: enhancement, type.Task

#86 Add CalendarVenue
  src/main/java/seedu/address/model/CalendarVenue.java
Labels: enhancement, type.Task

#112 Add CalendarAdmin, CalendarMeeting, CalendarPaperwork, CalenderViewing
  src/main/java/seedu/address/model/Calendar/CalendarAdmin.java
  src/main/java/seedu/address/model/Calendar/CalendarBidderId.java
  src/main/java/seedu/address/model/Calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/Calendar/CalendarPaperwork.java
  src/main/java/seedu/address/model/Calendar/CalendarPropertyId.java
  src/main/java/seedu/address/model/Calendar/CalendarTime.java
  src/main/java/seedu/address/model/Calendar/CalendarVenue.java
  src/main/java/seedu/address/model/Calendar/CalendarViewing.java
Labels: enhancement, type.Task

#114 Implement Property, UniquePropertyList and PropertyBook
  src/main/java/seedu/address/model/PropertyBook.java
  src/main/java/seedu/address/model/ReadOnlyPropertyBook.java
  src/main/java/seedu/address/model/id/IdManager.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/test/java/seedu/address/model/id/IdManagerTest.java
  src/test/java/seedu/address/model/id/IdTest.java
  src/test/java/seedu/address/model/price/PriceTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/testutil/properties/PropertyBuilder.java
  src/test/java/seedu/address/testutil/properties/TypicalProperties.java
Labels: type.Enhancements.Properties

#76 Add Bids Feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddBidCommand.java
  src/main/java/seedu/address/logic/commands/ListBidCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddBidCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/BidBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyBidBook.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/ui/BidCard.java
  src/main/java/seedu/address/ui/BidListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/view/BidListCard.fxml
  src/main/resources/view/BidListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabBar.fxml
  src/main/resources/view/TabPane.css
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: enhancement, type.Enhancements.Bids

#113 Add CalendarBookParser and CalendarAddCommandParser
  src/main/java/seedu/address/logic/parser/CalendarAddCommandParser.java
  src/main/java/seedu/address/logic/parser/CalendarBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/ReadOnlyMeetingManager.java
  src/main/java/seedu/address/model/calendar/CalendarAdmin.java
  src/main/java/seedu/address/model/calendar/CalendarBidderId.java
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/CalendarPaperwork.java
  src/main/java/seedu/address/model/calendar/CalendarPropertyId.java
  src/main/java/seedu/address/model/calendar/CalendarTime.java
  src/main/java/seedu/address/model/calendar/CalendarVenue.java
  src/main/java/seedu/address/model/calendar/CalendarViewing.java
  src/main/java/seedu/address/model/calendar/UniqueMeetingList.java
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/CalendarListPanel.java
Labels: enhancement, type.Task

#117 Add UniqueMeetingList and MeetingBook, add getters in CalendarMeeting
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/UniqueMeetingList.java
  src/main/java/seedu/address/model/calendar/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/calendar/exceptions/MeetingNotFoundException.java
Labels: enhancement, type.Task

#118 Read only meeting manager branch
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/ReadOnlyMeetingManager.java
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/CalendarTime.java
  src/main/java/seedu/address/model/calendar/CalendarVenue.java
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/CalendarListPanel.java
Labels: enhancement, type.Task

#120 Add bid storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/BidBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/BidBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedBid.java
  src/main/java/seedu/address/storage/JsonBidBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableBidBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, type.Enhancements.Bids

#116 Implement TypicalBidder/Seller, Bidder/Seller Builder, UniqueBiddle/SellerListTest, Bidder/SellerTest Modify Bidder/SellerAddressBook. Modify Bidder/SellerAddressBook
  src/main/java/seedu/address/model/BidderAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyBidderAddressBook.java
  src/main/java/seedu/address/model/ReadOnlySellerAddressBook.java
  src/main/java/seedu/address/model/SellerAddressBook.java
  src/main/java/seedu/address/model/person/ClientPerson.java
  src/main/java/seedu/address/model/person/UniqueBidderList.java
  src/main/java/seedu/address/model/person/UniqueSellerList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/BidderTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/model/person/UniqueBidderListTest.java
  src/test/java/seedu/address/model/person/UniqueSellerListTest.java
  src/test/java/seedu/address/testutil/BidderBuilder.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalBidder.java
  src/test/java/seedu/address/testutil/TypicalSeller.java
Labels: priority.Low, type.Enhancements.Persons

#128 Add Calendar Storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/calendar/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/calendar/JsonMeetingBookStorage.java
  src/main/java/seedu/address/storage/calendar/JsonSerializableMeetingBook.java
  src/main/java/seedu/address/storage/calendar/MeetingBookStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task

#131 Added Junit tests for CalendarVenue.java, CalendarMeeting.java, Calen…
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/CalendarVenue.java
  src/main/java/seedu/address/storage/calendar/JsonAdaptedMeeting.java
  src/test/java/seedu/address/model/calendar/CalendarBidderIdTest.java
  src/test/java/seedu/address/model/calendar/CalendarMeetingTest.java
  src/test/java/seedu/address/model/calendar/CalendarPropertyIdTest.java
  src/test/java/seedu/address/model/calendar/CalendarTimeTest.java
  src/test/java/seedu/address/model/calendar/CalendarVenueTest.java
Labels: type.Task

#129 Property storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/property/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/id/IdManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/bidder/Bidder.java
  src/main/java/seedu/address/model/property/Address.java
  src/main/java/seedu/address/model/property/IsClosedDeal.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/calendar/MeetingBookStorage.java
  src/main/java/seedu/address/storage/property/JsonAdaptedProperty.java
  src/main/java/seedu/address/storage/property/JsonPropertyBookStorage.java
  src/main/java/seedu/address/storage/property/JsonSerializablePropertyBook.java
  src/main/java/seedu/address/storage/property/PropertyBookStorage.java
  src/main/java/seedu/address/storage/sellerstorage/JsonSellerAddressBookStorage.java
  src/main/java/seedu/address/storage/sellerstorage/JsonSerializableSellerAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/id/IdManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/properties/PropertyBuilder.java
Labels: type.Enhancements.Properties

#130 Delete properties
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/DeletePropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/PropertyParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyBook.java
  src/main/java/seedu/address/model/property/PropertyModel.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/resources/view/property/PropertyListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancements.Properties

#133 Add JUnit Tests for AddCalendarMeeting and DeleteCalendarMeeting, Created TypicalMeetings, MeetingBuilder and updated CommandTestUtil with methods to filter MeetingLists
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/VenueContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/calendar/JsonMeetingBookStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: enhancement, type.Task

#149 Branch remove personui
  build.gradle
  src/main/java/seedu/address/model/person/bidder/Bidder.java
  src/main/java/seedu/address/model/person/seller/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/TabBar.fxml
Labels: priority.Low, type.Enhancements.Persons, type.Task

#154 Implement DeleteSeller/BidderCommand with JUNIT
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/biddercommands/DeleteBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/bidderparser/DeleteBidderCommandParser.java
  src/main/java/seedu/address/logic/parser/sellerparser/DeleteSellerCommandParser.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/bidder/DeleteBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/bidder/DeleteBidderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/seller/DeleteSellerCommandParserTest.java
Labels: enhancement, priority.High, type.Enhancements.Persons

#156 Implement FindBidderSeller and JUNIT Tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/biddercommands/FindBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/FindSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/bidderparser/FindBidderCommandParser.java
  src/main/java/seedu/address/logic/parser/sellerparser/FindSellerCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/bidder/FindBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/FindSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/bidder/FindBidderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/seller/FindSellerCommandParserTest.java
Labels: priority.High, type.Enhancements.Persons, type.Task

#151 Implement Bidder Seller JUNIT Command and Parser
  src/main/java/seedu/address/model/person/bidder/Bidder.java
  src/main/java/seedu/address/model/person/seller/Seller.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, type.Enhancements.Persons, type.Task

#165 Add edit function for meetings
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
Labels: enhancement, type.Task

#167 Add find meeting command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindMeetingCommandParser.java
  src/main/java/seedu/address/model/calendar/BidderIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/calendar/CalendarAdmin.java
  src/main/java/seedu/address/model/calendar/CalendarMeeting.java
  src/main/java/seedu/address/model/calendar/CalendarPaperwork.java
  src/main/java/seedu/address/model/calendar/CalendarViewing.java
  src/main/java/seedu/address/model/calendar/PropertyIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/calendar/TimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/calendar/UniqueMeetingList.java
  src/test/java/seedu/address/model/calendar/CalendarMeetingTest.java
Labels: type.Enhancements, type.Task

#169 Add list meeting command
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ViewCalendarCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCalendarParser.java
Labels: type.Enhancements, type.Task

#170 Add add property feature for DG
  docs/DeveloperGuide.md
  docs/images/property/AddPropertyIdManagementActivityDiagram.png
  docs/images/property/AddPropertySequenceDiagram.png
Labels: documentation

#172 Add Assert in CalendarBidderIdTest.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/calendar/CalendarBidderIdTest.java
Labels: enhancement, type.Task

#173 Update DG for Bidder Seller
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/biddersellerdiagrams/BidderDeleteActDiagram.puml
  docs/diagrams/biddersellerdiagrams/BidderDeleteSequenceDiagram.puml
  docs/diagrams/biddersellerdiagrams/BidderFindActDiagram.puml
  docs/images/BidderDeleteActivityDiagram.png
  docs/images/DeleteBidderSequenceDiagram.png
  docs/images/FindBidderSequenceDiagram.png
Labels: documentation, priority.High

#174 Add FindMeeting in DeveloperGuide.mg
  docs/DeveloperGuide.md
  docs/images/meeting/FindMeetingActivityDiagram.png
Labels: documentation

#176 Add update bid dg
  docs/DeveloperGuide.md
  docs/images/BidDeleteActivityDiagram.png
  docs/images/DeleteBidSequenceDiagram.PNG
  docs/images/ListBidSequenceDiagram.png
Labels: documentation

#178 Update DG with EditMeeting and MeetingTypes, Add Assert for CalendarPropertyIdTest
  docs/DeveloperGuide.md
  docs/images/meeting/editMeeting.png
  docs/images/meeting/typeOfMeeting.png
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/calendar/CalendarPropertyIdTest.java
Labels: documentation

#177 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#164 Refactor price
  src/main/java/seedu/address/logic/commands/bidcommands/EditBidCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/bidparser/AddBidCommandParser.java
  src/main/java/seedu/address/logic/parser/bidparser/EditBidCommandParser.java
  src/main/java/seedu/address/logic/parser/property/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/PropertyParserUtil.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/bidstorage/JsonAdaptedBid.java
  src/main/java/seedu/address/ui/bid/BidCard.java
  src/test/java/seedu/address/testutil/bids/BidBuilder.java
Labels: type.Task

#180 Edit property command
  src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/property/EditPropertyCommandParser.java
  src/test/java/seedu/address/logic/commands/property/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/PropertyCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/property/EditPropertyCommandParserTest.java
  src/test/java/seedu/address/testutil/property/EditPropertyDescriptorBuilder.java
Labels: type.Enhancements.Properties

#181 Fix bug for Add Bidder / Seller Command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/sellercommands/AddSellerCommand.java
  src/main/java/seedu/address/model/person/bidder/UniqueBidderList.java
  src/main/java/seedu/address/model/person/seller/UniqueSellerList.java
Labels: bug, priority.Medium, type.Bug, type.Task

#182 Update UI
  src/main/java/seedu/address/logic/commands/sellercommands/AddSellerCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabBar.fxml
Labels: priority.Medium, type.Enhancements, type.Task

#189 Change Calendar to Meeting in Test, fix bug add duplicate meeting dis…
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/meetingparser/FindMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meetingparser/SortMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Admin.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingComparator.java
  src/main/java/seedu/address/model/meeting/MeetingTimeComparator.java
  src/main/java/seedu/address/model/meeting/Paperwork.java
  src/main/java/seedu/address/model/meeting/Time.java
  src/main/java/seedu/address/model/meeting/Viewing.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: enhancement, type.Bug

#192 Enhance bid features
  build.gradle
  docs/DeveloperGuide.md
  docs/images/bids/BidDeleteActivityDiagram.png
  docs/images/bids/DeleteBidSequenceDiagram.PNG
  docs/images/bids/ListBidSequenceDiagram.png
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/bidcommands/AddBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/EditBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/FindBidCommand.java
  src/main/java/seedu/address/model/BidderModel.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/bid/BidComparator.java
  src/main/java/seedu/address/model/bid/BidContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/bidbook/BidBook.java
  src/main/java/seedu/address/model/bidbook/ReadOnlyBidBook.java
  src/main/java/seedu/address/model/bidderaddressbook/BidderAddressBook.java
  src/main/java/seedu/address/model/id/Id.java
  src/main/java/seedu/address/model/person/bidder/UniqueBidderList.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/storage/bidstorage/JsonBidBookStorage.java
  src/test/java/seedu/address/logic/commands/bids/AddBidCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/bids/AddBidCommandTest.java
  src/test/java/seedu/address/logic/commands/bids/BidCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/bids/EditBidCommandTest.java
  src/test/java/seedu/address/logic/commands/bids/FindBidCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/bids/EditBidDescriptorBuilder.java
  src/test/java/seedu/address/testutil/bids/TypicalBid.java
Labels: enhancement, help wanted, priority.High, type.Enhancements.Bids

#193 Improve UI and add commands for UI
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/bidcommands/AddBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/DeleteBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/EditBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/FindBidCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/AddBidderCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/DeleteBidderCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/EditBidderCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/FindBidderCommand.java
  src/main/java/seedu/address/logic/commands/calendarnavigation/NextCalendarNavigationCommand.java
  src/main/java/seedu/address/logic/commands/calendarnavigation/PrevCalendarNavigationCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/commands/property/AddPropertyCommand.java
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/FindSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/bidderparser/AddBidderCommandParser.java
  src/main/java/seedu/address/logic/parser/sellerparser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/bid_icon.png
  src/main/resources/images/bidder_icon.png
  src/main/resources/images/calendar_icon.png
  src/main/resources/images/prompter_icon.png
  src/main/resources/images/property_icon.png
  src/main/resources/images/seller_icon.png
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TabBar.fxml
  src/test/java/seedu/address/logic/parser/bidder/AddBidderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/seller/AddSellerCommandParserTest.java
Labels: enhancement, priority.Low, type.Enhancements, type.Task

#195 Fix UI messages for add, delete, find, sort Meeting Commands
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/SortMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/meetingparser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meetingparser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Time.java
  src/main/java/seedu/address/ui/meeting/MeetingCard.java
Labels: bug, type.Bug

#197 Update UserGuide.md with meeting commands
  docs/UserGuide.md
Labels: documentation

#198 Updated UG with delete, list, edit meeting commands
  docs/UserGuide.md
Labels: documentation

#194 Update UserGuide for Bidder, Seller, Calender and surprise UI improvement
  docs/UserGuide.md
  docs/images/CalendarPictures/Calendar_November.png
  docs/images/CalendarPictures/Calendar_October.png
  docs/images/OldUi.png
  docs/images/Ui.png
  src/main/java/seedu/address/model/person/ClientPerson.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/bid/BidCard.java
  src/main/java/seedu/address/ui/bid/BidListPanel.java
  src/main/java/seedu/address/ui/bidder/BidderCard.java
  src/main/java/seedu/address/ui/bidder/BidderListPanel.java
  src/main/java/seedu/address/ui/meeting/MeetingCard.java
  src/main/java/seedu/address/ui/meeting/MeetingListPanel.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/java/seedu/address/ui/seller/SellerCard.java
  src/main/java/seedu/address/ui/seller/SellerListPanel.java
  src/main/resources/images/address_icon.png
  src/main/resources/images/asking_price.png
  src/main/resources/images/houingtype.png
  src/main/resources/images/icon_time.png
  src/main/resources/images/id_icon.png
  src/main/resources/images/isrental.png
  src/main/resources/images/location_meeting.png
  src/main/resources/images/phone.png
  src/main/resources/images/tags.png
  src/main/resources/view/BidListCard.fxml
  src/main/resources/view/BidderListCard.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/SellerListCard.fxml
  src/main/resources/view/bid/BidListCard.fxml
  src/main/resources/view/bid/BidListPanel.fxml
  src/main/resources/view/bidder/BidderListCard.fxml
  src/main/resources/view/bidder/BidderListPanel.fxml
  src/main/resources/view/meeting/MeetingListCard.fxml
  src/main/resources/view/meeting/MeetingListPanel.fxml
  src/main/resources/view/property/PropertyListCard.fxml
  src/main/resources/view/seller/SellerListCard.fxml
  src/main/resources/view/seller/SellerListPanel.fxml
Labels: documentation, enhancement, type.Task

#199 Filter property
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/property/FindPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/property/FindPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/property/PropertyParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/price/PriceFilter.java
  src/main/java/seedu/address/model/property/AskingPricePredicate.java
  src/main/java/seedu/address/model/property/PropertyAddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/PropertyIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/PropertyIsClosedDealPredicate.java
  src/main/java/seedu/address/model/property/PropertyIsRentalPredicate.java
  src/main/java/seedu/address/model/property/PropertyTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/SellerIdContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/property/FindPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/PropertyCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/property/FindPropertyCommandParserTest.java
  src/test/java/seedu/address/model/price/PriceFilterTest.java
  src/test/java/seedu/address/model/price/PriceTest.java
  src/test/java/seedu/address/model/property/AskingPricePredicateTest.java
  src/test/java/seedu/address/model/property/PropertyAddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyIsClosedDealPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyIsRentalPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropertyTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/SellerIdContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/property/FindPropertyDescriptorBuilder.java
Labels: type.Enhancements.Properties

#200 Update UG for bids, added Junit tests for bid storage and parser, added auto sort to EditBidCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/bidcommands/AddBidCommand.java
  src/main/java/seedu/address/logic/commands/bidcommands/EditBidCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/bid/Bid.java
  src/main/java/seedu/address/model/bid/BidContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/bidbook/BidBook.java
  src/main/java/seedu/address/storage/bidstorage/JsonAdaptedBid.java
  src/test/data/JsonBidBookStorageTest/invalidAndValidBidBook.json
  src/test/data/JsonBidBookStorageTest/invalidBidBook.json
  src/test/data/JsonBidBookStorageTest/notJsonFormatBidBook.json
  src/test/data/JsonSerializableBidBookTest/duplicateBidBook.json
  src/test/data/JsonSerializableBidBookTest/invalidBidBook.json
  src/test/data/JsonSerializableBidBookTest/typicalBidBook.json
  src/test/java/seedu/address/logic/commands/bids/AddBidCommandTest.java
  src/test/java/seedu/address/logic/commands/bids/BidCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/bids/EditBidCommandTest.java
  src/test/java/seedu/address/logic/parser/bids/AddBidCommandParserTest.java
  src/test/java/seedu/address/logic/parser/bids/DeleteBidCommandParserTest.java
  src/test/java/seedu/address/logic/parser/bids/EditBidCommandParserTest.java
  src/test/java/seedu/address/logic/parser/bids/FindBidCommandParserTest.java
  src/test/java/seedu/address/model/bid/BidBookTest.java
  src/test/java/seedu/address/model/bid/BidTest.java
  src/test/java/seedu/address/model/bid/UniqueBidListTest.java
  src/test/java/seedu/address/storage/bids/JsonAdaptedBidTest.java
  src/test/java/seedu/address/storage/bidstorage/JsonAdaptedBidTest.java
  src/test/java/seedu/address/storage/bidstorage/JsonBidBookStorageTest.java
  src/test/java/seedu/address/storage/bidstorage/JsonSerializableBidBookTest.java
  src/test/java/seedu/address/testutil/bids/EditBidDescriptorBuilder.java
Labels: documentation, enhancement, type.Enhancements.Bids

#202 Add containsSellerId
  src/main/java/seedu/address/model/BidderModel.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SellerModel.java
  src/main/java/seedu/address/model/person/seller/UniqueSellerList.java
  src/main/java/seedu/address/model/selleraddressbook/SellerAddressBook.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: type.Enhancements.Persons, type.Task

#201 Update ug property
  docs/UserGuide.md
Labels: documentation

#204 Fix docs
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#205 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#206 Fix UserGuide.md and UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/property/PropertyListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: bug, type.Task

#208 Update StartTime.java, EndTime.java
  docs/DeveloperGuide.md
  docs/Gemfile.lock
  docs/team/christopher-lm.md
  docs/team/dianneloh9.md
  docs/team/johndoe.md
  docs/team/kormingsoon.md
  docs/team/marcon2509.md
  docs/team/munharsha.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/id/IdParserUtil.java
  src/main/java/seedu/address/logic/parser/meetingparser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meetingparser/EditMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meetingparser/FindMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meetingparser/MeetingParserUtil.java
  src/main/java/seedu/address/model/meeting/Admin.java
  src/main/java/seedu/address/model/meeting/Date.java
  src/main/java/seedu/address/model/meeting/DateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/EndTime.java
  src/main/java/seedu/address/model/meeting/EndTimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingComparator.java
  src/main/java/seedu/address/model/meeting/MeetingTimeComparator.java
  src/main/java/seedu/address/model/meeting/Paperwork.java
  src/main/java/seedu/address/model/meeting/StartTime.java
  src/main/java/seedu/address/model/meeting/StartTimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/TimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/Viewing.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/address/ui/meeting/MeetingCard.java
  src/main/resources/view/meeting/MeetingListCard.fxml
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/meeting/DateTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: enhancement, type.Task

#255 Fix Bug where meeting to be added checks if property and bidder id exists in the first place
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
Labels: bug, type.Bug

#256 Update error in date parsing
  docs/DeveloperGuide.md
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/team/christopher-lm.md
  docs/team/dianneloh9.md
  docs/team/johndoe.md
  docs/team/kormingsoon.md
  docs/team/marcon2509.md
  docs/team/munharsha.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meetingparser/AddMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Admin.java
  src/main/java/seedu/address/model/meeting/DateContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/EndTime.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingComparator.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/main/java/seedu/address/model/meeting/MeetingTimeComparator.java
  src/main/java/seedu/address/model/meeting/Paperwork.java
  src/main/java/seedu/address/model/meeting/StartTime.java
  src/main/java/seedu/address/model/meeting/Viewing.java
  src/main/java/seedu/address/model/meeting/exceptions/DuplicateMeetingException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/meeting/JsonAdaptedMeeting.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/meeting/MeetingCard.java
  src/main/resources/view/meeting/MeetingListCard.fxml
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/meeting/MeetingDateTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: enhancement, type.Task

#257 Update sample Util
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low, type.Bug

#258 Delete cascade bug
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/bidbook/BidBook.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
Labels: bug

#259 Implement cascading deleteCommand for bidder seller
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/bidcommands/AddBidCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/DeleteBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/DeleteSellerCommand.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/bidbook/BidBook.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/propertybook/PropertyBook.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/images/PropertyFree-Logo.png
  src/main/resources/images/bg-img-60.png
  src/main/resources/images/bg-img-70.png
  src/main/resources/images/bg-img.jpg
  src/main/resources/images/bg-img.png
  src/main/resources/images/diamond-bg.jpg
  src/main/resources/images/example.png
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MingSoonTheme.css
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TabBar.fxml
  src/main/resources/view/bid/BidListCard.fxml
  src/main/resources/view/bidder/BidderListCard.fxml
  src/main/resources/view/meeting/MeetingListCard.fxml
  src/main/resources/view/property/PropertyListCard.fxml
  src/main/resources/view/seller/SellerListCard.fxml
Labels: bug, type.Enhancements.Persons

#261 Added more tests and editmeetingbuilder and typicalmeetings
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meetingparser/AddMeetingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/MeetingCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meeting/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: priority.High, type.Enhancements

#260 Find property bugs
  src/main/java/seedu/address/logic/parser/property/PropertyParserUtil.java
  src/main/java/seedu/address/model/price/Price.java
Labels: bug

#264 Update Meeting.java to abstract class
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/test/java/seedu/address/logic/parser/meeting/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: enhancement

#263 Fix wrong error for non numeric price
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/price/Price.java
Labels: bug
