Repository AY2021S1-CS2103-W14-1/tp, pull requests merged in 2020-11, with the labels that each got.

#266 Edit property bug
  src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/propertybook/PropertyBook.java
  src/main/java/seedu/address/model/propertybook/PropertyModel.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: bug

#271 Update EditMeetingCommand.java Junit tests
  src/test/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/FindSellerCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: enhancement

#272 Created JUnit Test for the meeting parsers
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meetingparser/EditMeetingCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MeetingCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meeting/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/FindMeetingCommandParserTest.java
  src/test/java/seedu/address/testutil/FindMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeeting.java
Labels: enhancement, type.Enhancements

#275 Update Junit tests in FindMeetingCommandTest.java
  src/main/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommand.java
  src/main/java/seedu/address/model/meeting/Admin.java
  src/main/java/seedu/address/model/meeting/EndTime.java
  src/main/java/seedu/address/model/meeting/EndTimeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Paperwork.java
  src/main/java/seedu/address/model/meeting/Viewing.java
  src/test/java/seedu/address/logic/commands/MeetingCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/bidder/DeleteBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/bids/DeleteBidCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetingcommands/ListMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/meeting/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/FindMeetingCommandParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/meeting/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/meeting/FindMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/meeting/TypicalMeeting.java
Labels: enhancement

#277 Update PPP to add contibutions
  docs/team/munharsha.md
Labels: documentation

#278 Added @author to get contributions for the Junit tests in the meeting…
  docs/team/christopher-lm.md
  src/test/java/seedu/address/testutil/meeting/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/meeting/FindMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/meeting/TypicalMeeting.java
Labels: documentation, priority.Low

#279 Update PPP
  docs/UserGuide.md
  docs/team/marcon2509.md
  src/test/java/seedu/address/model/bid/UniqueBidListTest.java
Labels: documentation

#280 Property tests
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/commands/property/ListPropertyCommand.java
  src/main/java/seedu/address/logic/parser/id/IdParserUtil.java
  src/main/java/seedu/address/model/MeetingBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/bid/UniqueBidList.java
  src/main/java/seedu/address/model/bidbook/BidBook.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/price/PriceFilter.java
  src/main/java/seedu/address/model/property/Address.java
  src/main/java/seedu/address/model/property/AskingPricePredicate.java
  src/main/java/seedu/address/model/property/IsClosedDeal.java
  src/main/java/seedu/address/model/property/IsRental.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/PropertyName.java
  src/main/java/seedu/address/model/property/PropertyType.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/propertybook/PropertyBook.java
  src/test/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/property/AddPropertyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/property/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/PropertyCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/id/IdParserUtilTest.java
  src/test/java/seedu/address/logic/parser/property/DeletePropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/PropertyCommandInputBuilder.java
  src/test/java/seedu/address/logic/parser/property/PropertyParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/id/BidderIdTest.java
  src/test/java/seedu/address/model/id/PropertyIdTest.java
  src/test/java/seedu/address/model/id/SellerIdTest.java
  src/test/java/seedu/address/model/price/PriceFilterTest.java
  src/test/java/seedu/address/model/price/PriceTest.java
  src/test/java/seedu/address/model/property/AddressTest.java
  src/test/java/seedu/address/model/property/AskingPricePredicateTest.java
  src/test/java/seedu/address/model/property/IsClosedDealTest.java
  src/test/java/seedu/address/model/property/IsRentalTest.java
  src/test/java/seedu/address/model/property/PropertyNameTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/PropertyTypeTest.java
  src/test/java/seedu/address/model/property/UniquePropertyListTest.java
  src/test/java/seedu/address/model/propertybook/PropertyBookTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/property/TypicalProperties.java
Labels: priority.High, type.Enhancements.Properties, type.Task

#282 Update MeetingDateComparator.java naming
  src/main/java/seedu/address/logic/parser/meetingparser/SortMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/MeetingDateComparator.java
Labels: enhancement

#283 Update user guidetable
  docs/AboutUs.md
  docs/UserGuide.md
Labels: documentation

#284 Fix Bidder Seller
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/AppParameters.java
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/biddercommands/AddBidderCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/EditBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/sellerparser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ClientPerson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/bidder/Bidder.java
  src/main/java/seedu/address/model/person/bidder/UniqueBidderList.java
  src/main/java/seedu/address/model/person/seller/Seller.java
  src/main/java/seedu/address/model/person/seller/UniqueSellerList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TabBar.fxml
  src/main/resources/view/property/PropertyListCard.fxml
  src/test/java/seedu/address/logic/commands/bidder/AddBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/bidder/EditBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/bidder/DeleteBidderCommandParserTest.java
  src/test/java/seedu/address/model/person/BidderAddressBookTest.java
  src/test/java/seedu/address/model/person/BidderTest.java
  src/test/java/seedu/address/model/person/SellerAddressBookTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/model/person/UniqueBidderListTest.java
  src/test/java/seedu/address/model/person/UniqueSellerListTest.java
  src/test/java/seedu/address/testutil/bidder/BidderBuilder.java
  src/test/java/seedu/address/testutil/bidder/TypicalBidder.java
  src/test/java/seedu/address/testutil/seller/EditSellerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/seller/SellerBuilder.java
  src/test/java/seedu/address/testutil/seller/TypicalSeller.java
Labels: bug

#285 Update JUNIT Tests for Bidder Seller
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/bidderparser/EditBidderCommandParser.java
  src/main/java/seedu/address/logic/parser/sellerparser/EditSellerCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/meeting/MeetingCard.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/resources/images/date-icon.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MingSoonTheme.css
  src/main/resources/view/meeting/MeetingListCard.fxml
  src/main/resources/view/property/PropertyListCard.fxml
  src/test/java/seedu/address/logic/NextCalendarNavigationCommandTest.java
  src/test/java/seedu/address/logic/PrevCalendarNavigationCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/bidder/BidderCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/bidder/EditBidderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/seller/EditSellerCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/seller/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/bidder/EditBidderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/bidder/TypicalBidder.java
  src/test/java/seedu/address/testutil/seller/EditSellerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/seller/TypicalSeller.java
Labels: bug, priority.High

#286 Ug update round2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/biddercommands/ListBidderCommand.java
Labels: documentation

#287 Fix Bidder Seller bug and Update UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/biddercommands/EditBidderCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/ListBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/ListSellerCommand.java
  src/main/java/seedu/address/model/person/bidder/Bidder.java
  src/test/java/seedu/address/logic/commands/bidder/EditBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/EditSellerCommandTest.java
Labels: bug, documentation

#288 Update editbid
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/bidcommands/EditBidCommand.java
  src/main/java/seedu/address/model/bid/Bid.java
Labels: bug, type.Bug, type.Enhancements.Bids

#290 Update UG Meeting Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meetingparser/FindMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/test/java/seedu/address/logic/parser/meeting/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/FindMeetingCommandParserTest.java
Labels: documentation

#291 Add limit length for Name and Phone
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: bug, type.Enhancements.Persons

#292 Update ug
  docs/UserGuide.md
  docs/team/dianneloh9.md
Labels: documentation

#293 Fix warning symbols
  docs/UserGuide.md
Labels: documentation

#294 Updated UG for Meeting Section
  docs/UserGuide.md
Labels: documentation

#295 Update UserGuide.md and Add Key Press Navigation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/deleteCommandDiagram/deleteBidderCommandSequenceDiagram.png
  docs/images/deleteCommandDiagram/deleteCommandSequenceDiagram.png
  docs/images/deleteCommandDiagram/deleteSellerCommandSequenceDiagram.png
  docs/images/modelDiagram/BidderSellerModelDiagram.png
  docs/images/modelDiagram/IdModelDiagram.png
  docs/images/modelDiagram/ModelClassDiagram.png
  docs/images/uidiagram/Ui-Component-Breakdown.png
  docs/images/uidiagram/Ui-Component-HelpWindow.png
  docs/images/uidiagram/Ui-Component.png
  docs/images/uidiagram/uidiagram.png
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/SortMeetingCommand.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/TabBar.fxml
Labels: documentation, enhancement

#296 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/images/modelDiagram/BidderSellerModelDiagram.png
  docs/images/modelDiagram/ModelClassDiagram.png
  src/main/java/seedu/address/ui/CommandBox.java
Labels: documentation

#297 Update dg2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddCommandSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/AutoSortBidSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/modelDiagram/BidModelDiagram.png
Labels: documentation

#298 Update DeveloperGuide.md with Ui Implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/modelDiagram/BidderSellerModelDiagram.png
  docs/images/uidiagram/autoTabBarActivityDiagram.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: documentation

#303 Update DG
  docs/DeveloperGuide.md
  docs/images/SortSequenceDiagram.png
  docs/images/Storage/StorageDiagram.png
  docs/images/Storage/StorageDiagramFurther.png
  docs/images/StorageClassDiagram.png
  docs/images/meeting/MeetingModel.png
  docs/team/munharsha.md
Labels: documentation

#299 Update DG for property
  docs/DeveloperGuide.md
  docs/images/addCommandDiagram/addPropertyCommandSequenceDiagram.png
  docs/images/addCommandDiagram/addPropertyIdManagementActivityDiagram.png
  docs/images/deleteCommandDiagram/cascadeDeleteProperty.png
  docs/images/deleteCommandDiagram/deletePropertyCommandSequenceDiagram.png
  docs/images/findCommandDiagram/findCommandSequenceDiagram1.png
  docs/images/findCommandDiagram/findCommandSequenceDiagram2.png
  docs/images/findCommandDiagram/priceFilterClassDiagram.png
  docs/images/modelDiagram/PropertyModelDiagram.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#313 Updated UG with logic and edit components
  docs/DeveloperGuide.md
  docs/images/DeleteMeetingSD.jpg
  docs/images/EditXYZSD.jpg
  docs/images/ValidityCheckSD.jpg
Labels: documentation

#316 Update user guide
  docs/UserGuide.md
Labels: documentation

#317 Fix Edit Meeting bug, user able to edit an existing meeting with non-…
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meetingcommands/AddMeetingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/meetingcommands/EditMeetingCommandTest.java
  src/test/java/seedu/address/testutil/meeting/TypicalMeeting.java
Labels: bug

#322 Update diagrams and fix bidder seller edit bug
  docs/UserGuide.md
  docs/images/deleteCommandDiagram/deleteBidderCommandSequenceDiagram.png
  docs/images/deleteCommandDiagram/deleteCommandSequenceDiagram.png
  docs/images/deleteCommandDiagram/deleteSellerCommandSequenceDiagram.png
  docs/images/modelDiagram/ModelClassDiagram.png
  docs/images/uidiagram/Ui-Component.png
  src/main/java/seedu/address/logic/commands/biddercommands/EditBidderCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/bidderaddressbook/BidderAddressBook.java
  src/main/java/seedu/address/model/bidderaddressbook/BidderModel.java
  src/main/java/seedu/address/model/person/ClientPerson.java
  src/main/java/seedu/address/model/person/bidder/UniqueBidderList.java
  src/main/java/seedu/address/model/person/seller/UniqueSellerList.java
  src/main/java/seedu/address/model/selleraddressbook/ReadOnlySellerAddressBook.java
  src/main/java/seedu/address/model/selleraddressbook/SellerAddressBook.java
  src/main/java/seedu/address/model/selleraddressbook/SellerModel.java
  src/test/java/seedu/address/logic/commands/bidder/EditBidderCommandTest.java
  src/test/java/seedu/address/logic/commands/seller/EditSellerCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: bug, documentation

#321 Property dg
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AddBidCommandSequenceDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteMeetingSD.jpg
  docs/images/DeleteMeetingSD.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/Storage/StorageDiagram.png
  docs/images/Storage/StorageDiagramFurther.png
  docs/images/addCommandDiagram/AddPropertyCommandSequenceDiagram.png
  docs/images/addCommandDiagram/addPropertyCommandSequenceDiagram.png
  docs/images/deleteCommandDiagram/cascadeDeleteProperty.png
  docs/images/meeting/MeetingModel.png
  docs/images/modelDiagram/IdModelDiagram.png
  docs/images/storage/StorageDiagram.png
  docs/images/storage/StorageDiagramFurther.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#324 Update UserGuide and ListENTITYCommand message command
  docs/UserGuide.md
  docs/team/kormingsoon.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/bidcommands/ListBidCommand.java
  src/main/java/seedu/address/logic/commands/biddercommands/EditBidderCommand.java
  src/main/java/seedu/address/logic/commands/meetingcommands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/property/ListPropertyCommand.java
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
Labels: documentation

#326 Update meeting start time branch
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: documentation

#327 Updated PPS, meetingdate, ParserUtil Methods
  docs/team/christopher-lm.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/MeetingDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/meeting/AddMeetingCommandParserTest.java
Labels: bug, documentation

#328 Refactor property
  docs/UserGuide.md
  docs/images/deleteCommandDiagram/deletePropertyCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/property/DeletePropertyCommand.java
  src/main/java/seedu/address/logic/commands/property/FindPropertyCommand.java
  src/main/java/seedu/address/logic/parser/property/FindPropertyCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/property/Address.java
  src/main/java/seedu/address/model/property/PropertyName.java
  src/main/java/seedu/address/model/property/PropertyType.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/main/java/seedu/address/model/propertybook/PropertyBook.java
  src/test/java/seedu/address/logic/commands/property/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/FindPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/property/PropertyCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/property/FindPropertyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/PropertyCommandInputBuilder.java
  src/test/java/seedu/address/logic/parser/property/PropertyParserUtilTest.java
  src/test/java/seedu/address/model/property/AddressTest.java
  src/test/java/seedu/address/model/property/PropertyNameTest.java
  src/test/java/seedu/address/model/property/PropertyTypeTest.java
  src/test/java/seedu/address/model/propertybook/PropertyBookTest.java
  src/test/java/seedu/address/testutil/property/FindPropertyDescriptorBuilder.java
Labels: bug

#333 Update pp pv2
  docs/team/marcon2509.md
Labels: documentation

#336 Update spellling munharsha.md
  docs/team/munharsha.md
Labels: documentation

#335 Update PPP, change in key press function, updated UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/dianneloh9.md
  docs/team/kormingsoon.md
  docs/team/marcon2509.md
  src/main/java/seedu/address/logic/commands/sellercommands/EditSellerCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: documentation, type.Bug

#339 updated PPP for marcon2509
  docs/team/marcon2509.md
Labels: documentation

#341 Fix spelling ppp branch
  docs/DeveloperGuide.md
  docs/team/munharsha.md
Labels: documentation

#343 Updated DG with use cases
  docs/DeveloperGuide.md
  docs/images/EditXYZSD.jpg
  docs/team/christopher-lm.md
Labels: documentation

#342 Dg manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/dianneloh9.md
Labels: documentation

#347 Update Name in munharsha.md
  docs/team/munharsha.md
Labels: documentation

#348 Updated PPP
  docs/team/christopher-lm.md
Labels: documentation

#346 dg-manual-testing
  docs/DeveloperGuide.md
Labels: bug, documentation

#345 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kormingsoon.md
Labels: documentation

#349 Update name in munharsha.md
  docs/team/munharsha.md
Labels: documentation

#351 Update ppp
  docs/team/dianneloh9.md
Labels: documentation

#353 Update name munharsha.md
  docs/team/munharsha.md
Labels: documentation

#350 updated PPP
  docs/team/marcon2509.md
Labels: documentation

#352 Fix PPP
  docs/team/christopher-lm.md
Labels: documentation

#354 Update PPP
  docs/team/kormingsoon.md
Labels: documentation

#362 Fix PPP
  docs/team/christopher-lm.md
Labels: documentation

#364 Shorten PPP
  docs/team/christopher-lm.md
Labels: documentation

#366 Shorten PPP
  docs/team/christopher-lm.md
Labels: documentation

#368 Shorten PPP
  docs/team/christopher-lm.md
Labels: documentation
